# Generated by Django 6.0.4 on 2026-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_timer_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsession',
            name='timer_paused_at',
            field=models.DateTimeField(blank=True, help_text='Set when the host pauses the timer; cleared on resume.', null=True),
        ),
    ]
